### ISSUE TITLE
Support for region variations of same language

### ISSUE THREAD

**Issue by Manuiq** [betterme-dev/Localizer-Android#3]
At the moment resource folders that are generated for local variation of languages from Poeditor language codes are not valid for Android :( . For example chinese (Hong-Kong) is placed inside **values-zn-hk** but a valid folder name should be **values-zn-rHK**  (as described [here](https://fabiohub.wordpress.com/2016/12/31/chinese-locale-in-android/))

**Comment by constmikhailovskiy** [comment]
Added regions support in 1.0.4 & updated the docs.
